### ISSUE TITLE
[Enhancement] Auto-generated file extension

### ISSUE THREAD

**Issue by RollyPeres** [rrousselGit/freezed#101]
Is there any solid reason for not following the existing dart naming conventions for generated files?
I suggest naming freezed generated files using `model.f.dart` to align with the existing `model.g.dart` naming convention.

**Comment by rrousselGit** [comment]
The way these naming works is based on what type of "builder" the code-generator is using.

`.g.dart` is for when a code-generator supports other generators using the same output file, where everything gets merged into one.\
`.whatever.dart` is for when it is _not_ supported, and a single generator outputs to that file.

Freezed falls on the second case (as a requirement for json_serializable support)
Using `.f.dart` instead of `.freezed.dart` could mean that if another generator also wants `.f.dart`, we'd have name conflict.\
It is therefore more logical to use the library name

**Comment by RollyPeres** [comment]
I'm aware of that, but like you said about package name conflicts...what happens when there's a package name conflict ? well, someone will have to find a new name. Why not apply the same rule for extension?

**Comment by rrousselGit** [comment]
Package names are unique.

**Comment by RollyPeres** [comment]
If there's no way of pre validating generator extension when publishing I guess being more specific is the way to go.

**Comment by rrousselGit** [comment]
Closing this since I don't think changing it is a good idea (and is not very useful anyway)
