### ISSUE TITLE
Remove mandatory orElse

### ISSUE THREAD

**Issue by nonoyona** [rrousselGit/freezed#302]
The orElse option in maybeWhen or maybeMap in unions often is not necessary.
Therefore it is only boilerplate code that increases entropy.

I would like to have it removed because it would not decrease experience if its needed every call.

What are your thoughts about that

**Comment by rrousselGit** [comment]
The `orElse` is mandatory because of non-nullable types.

Maybe you want a `whenOrNull`?

**Comment by nonoyona** [comment]
Yeah, that would be a compromise.
It would fit my needs very well.

**Comment by Jjagg** [comment]
`maybeMap` and `maybeWhen` could behave similarly to [`Iterable.firstWhere`](https://api.dart.dev/stable/2.10.5/dart-core/Iterable/firstWhere.html). It throws a `StateError` when nothing matches and `orElse` is omitted.

That works for a use-case I have right know, where I can exclude some options of my union because of an API contract.

**Comment by rrousselGit** [comment]
Throwing is against the principle of Freezed which is to promote compile
safety

**Comment by harkairt** [comment]
I'd also like a `whenOrNull`, maybe it is a bad practice, but I find myself writing `orElse: () => null`s a couple of times

**Comment by rrousselGit** [comment]
With null-safety, a `whenOrNull` makes sense. I'll see what I can do.

**Comment by rrousselGit** [comment]
I have added a whenOrNull, so I'll close this
