### ISSUE TITLE
Stack overflow exception

### ISSUE THREAD

**Issue by fryette** [rrousselGit/freezed#413]
Have the same exception with the latest version as below:
https://github.com/rrousselGit/freezed/issues/118

What is more interesting if I remove reference(_import_) everything goes very well.
So, now it's impossible to generate freezed classes where factory constructor has other freezed classes.

Why freezed look into _import_ at all?

**Comment by SunlightBro** [comment]
Can you provide a minimal example to reproduce the issue ?
Haven't had much time to work with this since null-safety. but will have a look at it.

**Comment by fryette** [comment]
@SunlightBro will try to create and share today later

**Comment by fryette** [comment]
@SunlightBro 
Ah, after few hours I finally found the root cause

If you have index.dart like that:

```
export 'test_model.dart';
export 'index.dart';
```

generation will fail. 

Of course, it's my fault but it was really hard to find(on 1.10 everything works fine).
I uploaded sample project(lib folder and packages folder), you just need to create new project and extract files to root

[Archive.zip](https://github.com/rrousselGit/freezed/files/6217563/Archive.zip)

**Comment by SunlightBro** [comment]
Hey sry for the late reply.

As you already mentioned the issue is that index.dart export itself and that produces an issue when compiling the build script:
> [WARNING] ApplyBuilders:
Configuring `swagger_dart_code_generator:swagger_dart_code_generator` in target `repositories:repositories` but this is not a known Builder

So this is not freezed specific, but has todo with your swagger_dart_code_generator defined in your `build.yaml`

So I think this issue can be closed.

@fryette FYI. Consider only using your `repositories.dart` file to export all the classes of your package, 
so that your apps that depend on your package only have to import one file, to have everything:
```dart
import 'package:repositories/repositories.dart';
```

**Comment by ElteHupkes** [comment]
A bit late to the party here, but I just encountered a stack overflow when using freezed due to another package I'm using that had some circular imports (or rather, a file was importing / exporting itself). That's clearly silly, but given that it's legal in Dart, should steps be taken to prevent a stack overflow in freezed in this case?
