### ISSUE TITLE
Default value doesn't work on doubles and integers

### ISSUE THREAD

**Issue by CoderUni** [rrousselGit/freezed#438]
**Describe the bug**

The variable doesn't get initialized with the default value when calling `fromJson()`. Here is how the json looks like:
```json
{
 "otherValue": 1,
}
```

**To Reproduce**

```dart
@freezed
abstract class Model with _$Model {
  factory Model({
    @Default(0.0) @JsonKey(name: 'value') double? value,
    @Default(0) @JsonKey(name: 'otherValue') int? otherValue,
  }) = Model;

  factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);
}
```

**Expected behavior**

The value of `_model.value` should be 0.0 but its value is null.

**Comment by SunlightBro** [comment]
This is expected behaviour, **definitely confusing**, but expected.

The `@Default()` annotation from freezed **only** creates a new`@JsonKey` annotation for the `fromJson`  constructor, **except** if it's already defined. 
That way it's possible to have two different default values, for fromJson and the default constructor. 

### Here a full example:
```dart
@freezed
class Model with _$Model {
  factory Model({
    int? val,
    @Default(0) int? defaultVal,
    @JsonKey(defaultValue: 0) int? jsonKeyVal,
    @Default(1) @JsonKey(defaultValue: 2) int? diffDefaultVal,
    @Default(0) @JsonKey(name: 'issueVal') int? issueVal, // <= your specific case
  }) = _Model;

  factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);
}
```
in the main:
```dart
import 'model/model.dart';

void main() {
  final jsonModel = Model.fromJson(<String, dynamic>{});
  // jsonModel: Model(val: null, defaultVal: 0, jsonKeyVal: 0, diffDefaultVal: 2, issueVal: null)
  final factoryModel = Model();
  // factoryModel: Model(val: null, defaultVal: 0, jsonKeyVal: null, diffDefaultVal: 1, issueVal: 0)
}
```

@CoderUni for your case you could either define your default twice:
`@Default(0) @JsonKey(name: 'value', defaultValue: 0) int? value,`
or because name is identical to you parameters name, you can remove JsonKey:
`@Default(0) int? value,`

**Comment by CoderUni** [comment]
@SunlightBro 
Thanks for your help, it works. I thought `@Default()` will also set the `fromJson`'s default as well.

**Comment by rohan20** [comment]
> @SunlightBro
> Thanks for your help, it works. I thought `@Default()` will also set the `fromJson`'s default as well.

I thought so too. Took a while to understand. 

@rrousselGit As per the [docs for @Default](https://pub.dev/packages/freezed#default-values):

> NOTE:
> If you are using serialization/deserialization, this will automatically add a @JsonKey(defaultValue: <something>) for you.

Shouldn't:

```dart
@Default(0) @JsonKey(name: 'otherValue') int? otherValue,
```

be the same as:
```dart
@Default(0) @JsonKey(name: 'otherValue', defaultValue: 0) int? otherValue,
```

?
