### ISSUE TITLE
support for all @JsonSeriazable() paramaters

### ISSUE THREAD

**Issue by hosamkora** [rrousselGit/freezed#49]
ex:
```dart
@JsonSerializable(fieldRename: FieldRename.snake)
class Person {
 // will convert camal case to snake case automatically 
//  equivelant to JsonKey(name:"first_name")
  String firstName;
}
```
suggestion:
```dart
@SerializableFreezed(fieldRename: FieldRename.snake)
class Person {
  factory Person(String firstName) = _Person;
}
```

**Comment by doc-rj-celltrak** [comment]
Thanks for the great package, We're using this instead of built_value, and we're using it with json_serializable. I have a question though...

I need to use this guy: @JsonSerializable(ignoreUnannotated: true)

Is there a way to use ignoreUnannotated or any other class-level json annotations while using @freezed?  Currently, it seems to be generating an extra FromJson, when i do this:

@freezed @JsonSerializable(ignoreUnannotated: true)

...which probably makes sense, but it means I have to put @JsonKey(ignore: true) all over the place rather than using @JsonSerializable.

Thanks in advance for any suggestions.

**Comment by doc-rj-celltrak** [comment]
Ah, and i just saw this: #50  ... are there any plans in the near future? Thanks!

**Comment by rrousselGit** [comment]
#50 should be pretty simple to do (as it's done already with parameters).
I'm kinda working on other stuff at the moment though.

Feel free to make a pull request!
