### ISSUE TITLE
Adding documentation comments to properties has no effect

### ISSUE THREAD

**Issue by Wizzel1** [rrousselGit/freezed#498]
**Describe the bug**
I was trying to add documentation for my class as written in the Freezed Documentation but these comments to not appear on the properties. 

**To Reproduce**

This is the class i'd like to document

```
@freezed
// ignore: prefer_mixin
class Competency with _$Competency, WithDescription {
  const Competency._();
  const factory Competency({
    ///The ID of this [Competency]
    required String id,

    ///The name of this [Competency]
    required String name,

    ///The description of this [Competency]
    String? description,
  }) = _Competency;

  @override
  String? get description => description;

  @override
  String get name => name;

  factory Competency.fromJson(Map<String, dynamic> json) =>
      _$CompetencyFromJson(json);
}
```

**Expected behavior**
I was expecting to see my documentation when I hover over the properties of my class/ an object of it.

**Comment by Wizzel1** [comment]
Well actually it does have an effect. Apparently it adds the documentation to the getter. What about class property documentation? 

For example when I want to create a new instance like 

`final competency = Competency(id: <-- how to get documentation here)`

**Comment by rrousselGit** [comment]
The comments do appear on class properties.
What you're describing isn't class properties but constructor parameters.

IDEs do not support documentation on constructor/function parameters. 
This isn't something that Freezed can do anything about. It's a missing feature on IDEs.
People asked for comments on parameters before, but this isn't something the Dart team is in favour.


In any case, since there's nothing that Freezed can do, I'm going to close this

**Comment by Wizzel1** [comment]
Alright, thanks for clarifying.
