### ISSUE TITLE
freezed_annotation @DeepCollectionEquality

### ISSUE THREAD

**Issue by frogman1189** [rrousselGit/freezed#547]
**Describe the bug**
@DeepCollectionEquality() annotation does nothing. This issue `https://github.com/rrousselGit/freezed/issues/227` suggests that this is desired (?)
So either why is the annotation there, and if there's a good reason I feel like it should be documented, or its a bug and should be fixed

**To Reproduce**

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'union.freezed.dart';

@freezed
class Union with _$Union {
  const factory Union.list({
    @DeepCollectionEquality() required UnmodifiableListView list,
  }) = _List;

  const factory Union.set({
    @DeepCollectionEquality() required UnmodifiableSetView set,
  }) = _Set;
}

void main() {
  final list = [1,2,3];

  print(Union.list(list: UnmodifiableListView(list)) == Union.list(list: UnmodifiableListView(list)));

  final set = {1, 2, 3};
  print(Union.set(set: UnmodifiableSetView(set)) == Union.set(set: UnmodifiableSetView(set)));
}
```

**Expected behavior**
should output
```
true
true
```

**Comment by rrousselGit** [comment]
There is no such annotation. What you used (DeepCollectionEquality) is not an annotation, but a normal Dart class exposed by `package:collection` – which `freezed_annotation` exports because generated code uses it.

The issue you linked mentions that this feature request was rejected, so there is no such thing.
