### ISSUE TITLE
Avoid LoC for classes with lot of constructors

### ISSUE THREAD

**Issue by obitodarky** [rrousselGit/freezed#554]
**Describe the bug**
My class has around 50 factory constructors each with around 5-6 params that make up to 600-700 lines of code that will generate the `.freezed.dart` file. 

In turn, my `.freezed.dart` file turns out to be around **70-80k lines of code**. Adding a single param to the factory constructor adds around 200 lines of code to the generated file. 
What I see is that in the generated file, `when`, `maybeWhen`, `map`, `maybeMap` seem to be the same for all the generated classes. 

This seems to be a problem because there's a lot of duplicate lines of code for these generated models and I would like to avoid that. 

Here is a small/sample snippet:
```dart
abstract class SomeClass with _$SomeClass {
  const factory SomeClass(int value, {
    @required String url,
    @nullable Object obj,
  }) = Data;
  const factory SomeClass.loading() = Loading;
  const factory SomeClass.error([String message]) = ErrorDetails;

  const factory SomeClass.test(int value, {
    @required String str1,
    @nullable Object obj1,
    @nullable String str2,
    @nullable Object obj2,
  }) = Value;

....
```

**Expected behavior**
Is there a good practice I can maintain to avoid such a long generated file? I'm having issues with the deployment and the CI/CD currently with this.

**Comment by rrousselGit** [comment]
>  I'm having issues with the deployment and the CI/CD currently with this.

Could you expand on what this problem is?

Rather than the number of lines, this seems to be your problem.

**Comment by fryette** [comment]
@rrousselGit I have a similar problem.
I have a giant project with few thousand freezed classes.
After building apk I found that just the source code of freezed files(I moved all freezed files to a separate package) was more than 15MB. Yes, we can enable obfuscation, but now for Linux its not working at all(I have to support Linux as well).

**Comment by rrousselGit** [comment]
There's not much we can factorize in the generated code. Sure, there's a lot of duplicates, but they aren't duplicates that can be avoided, since they are function/constructor prototypes.   
We'd have to disable features to reduce the size of the generated code. But I don't see why that's helpful.

To begin with, Dart is tree-shaked, so the existence or not of a `when` method if you're not using it won't impact your bundle size.

What do you expect from this issue exactly and why?

**Comment by fryette** [comment]
@rrousselGit agree with you
If it is impossible to refactor to reduce the size then nothing to do.

**Comment by ganeshrvel** [comment]
@rrousselGit

We are facing a lot of problems because of the freezed file size (3MB and 79k lines).


1) Build runner is taking too much time to complete (yes i have setup build.yaml file and even the --filter-output is used)
2) Code insights **AREN'T** working anymore due to the file size
3) Dart static analyzer and Git has started acting weird lately.


We aren't concerned too much about the final build size, dart should be taking care of it but  the development has become very difficult lately. 

There could be some parameters we could use to disable certain features.

**Comment by ganeshrvel** [comment]
> I have a giant project with few thousand freezed classes.

I am feeling very sorry for you man!

**Comment by obitodarky** [comment]
> There's not much we can factorize in the generated code. Sure, there's a lot of duplicates, but they aren't duplicates that can be avoided, since they are function/constructor prototypes.

Is there anything we can do from our end to reduce the lines of code as much as we can? As in following some practices?

**Comment by rrousselGit** [comment]
You may want to avoid having one Freezed class with 50 constructors
It's quite likely that you can split this class in multiple smaller ones.

You most likely could use generics or composition to achieve the same effect

**Comment by rrousselGit** [comment]
With the ability to customize the output, I think this can be closed. Disabling `map` or `when` can decrease significantly the generated code
