### ISSUE TITLE
Custom line-length for generated code

### ISSUE THREAD

**Issue by fzyzcjy** [rrousselGit/freezed#610]
Hi thanks for the wonderful lib! I would appreciate it if the generated `.g.dart` code could be 120-character in width. I can make a PR for this.

How to implement this: https://github.com/dart-lang/build/issues/3250

**Comment by rrousselGit** [comment]
I don't really like this. IMO the generated code should not have to respect the style of the project in which it is generated in, as the generated code shouldn't be visible to begin with.

**Comment by fzyzcjy** [comment]
Hi thanks for the reply. My use case is: I will run `dart format --line-length 120` to my *whole* project regularly (both in CI and when developing), and use that as code formatting. Could you please provide some suggestions?

**Comment by rrousselGit** [comment]
Running it in dev shouldn't have any impact

And the CI shouldn't verify generated files. Maybe consider deleting generated files before checking their format

**Comment by fzyzcjy** [comment]
> And the CI shouldn't verify generated files. Maybe consider deleting generated files before checking their format

Good suggestion

> Running it in dev shouldn't have any impact

Seems that all .g.dart and .freezed.dart are *reformatted* from the original 80-length to 120-length :(

**Comment by rrousselGit** [comment]
> Seems that all .g.dart and .freezed.dart are reformatted from the original 80-length to 120-length :(


To begin with, you probably want the dev environment to only format modified files instead of the whole project

**Comment by fzyzcjy** [comment]
Sounds reasonable, but those generated files are changed (though automatically but codegen) as well

**Comment by rrousselGit** [comment]
I personally don't plan on working on this.

If you really want this, I'd be happy to review a PR. Otherwise can we close this? :smile:

**Comment by ekuleshov-idexx** [comment]
The standard `dart format` command accepts list of files/folders for reformatting and it allows to fail build when project's formatting doesn't match the standard one. Unfortunately the `dart format` does not have an option to exclude generated files.

So, currently we have to reformat all generated files manually in order to pass our build.

Please reconsider adding an option to specify line length for the generated code and maybe also use the `DartFormatter` from `dart_style` to format generated code.
