### ISSUE TITLE
Support import alias

### ISSUE THREAD

**Issue by alvistar** [rrousselGit/freezed#70]
Hi,
simple code:

```dart
import 'package:dart_algorand/algod.dart' as algod;

@freezed
abstract class BaseState with _$BaseState {
  factory BaseState({algod.Account accountInfo}) = _BaseState;
}
```

It will not work as generated file will use just Account without prefix algod.

Hope it's clear enough.

a.

**Comment by fernando-s97** [comment]
Any workarounds while this is not fixed?

**Comment by goevexx** [comment]
> Any workarounds while this is not fixed?

If you need to use aliases e.g. because you use multiple imports with same classnames, just as it is the problem in my case, i don't see a way around renaming classes. 
I use dartz and an own imported class called Order in my freezed class. But Order is already defined by dartz as well. So I need to use aliases. And aliases don't work with freezed. So correct me if I'm wrong, but I need to rename my Order class to use it?

Other workarounds appreciated!

**Comment by fernando-s97** [comment]
> > Any workarounds while this is not fixed?
> 
> If you need to use aliases e.g. because you use multiple imports with same classnames, just as it is the problem in my case, i don't see a way around renaming classes.
> I use dartz and an own imported class called Order in my freezed class. But Order is already defined by dartz as well. So I need to use aliases. And aliases don't work with freezed. So correct me if I'm wrong, but I need to rename my Order class to use it?
> 
> Other workarounds appreciated!

In my case not even this will work, because the two conflicting class names are from two different packages

**Comment by matekdk** [comment]
This bug is marked as closed, but as of 18th Sep. 2021 and version 0.14.5 - it is not (fully fixed). Example:

```
/// importing library from another package with prefix
import 'package:some_package/core.dart' as core;

@freezed
class ProfileEvent with _$ProfileEvent {
  /// note that core.Profile is _also_ a freezed class
  const factory ProfileEvent.changeTo({required core.Profile profile}) =
      _ChangeTo;
}
```

Now, this will generate the following syntax errors in .freezed file:

```
abstract class _$ChangeToCopyWith<$Res> {
  factory _$ChangeToCopyWith(_ChangeTo value, $Res Function(_ChangeTo) then) =
      __$ChangeToCopyWithImpl<$Res>;
  $Res call({core.Profile profile}); // note: generator adds prefix correctly here

  $ProfileCopyWith<$Res> get profile; // syntax error: Undefined class '$ProfileCopyWith'.
}
class __$ChangeToCopyWithImpl<$Res> extends _$ProfileEventCopyWithImpl<$Res>
    implements _$ChangeToCopyWith<$Res> {
/// [ .. lines removed .. ]
  @override
  $ProfileCopyWith<$Res> get profile { // Syntax error: Undefined class '$ProfileCopyWith'.
    return $ProfileCopyWith<$Res>(_value.profile, (value) { // same syntax error as above
      return _then(_value.copyWith(profile: value));
    });
  }
```

Currently, my workaround is to edit the .freezed files manually adding the prefix everywhere where there are syntax errors: 

`core.$ProfileCopyWith<$Res>`

@rrousselGit : Please advise if I should open a new bug for this, alternatively, this bug probably should be repoened.

**Comment by rrousselGit** [comment]
Yes please open a new issue

**Comment by alectogeek** [comment]
The bug is not fixed yet. Is there a new issue opened?

**Comment by isawk** [comment]
Alternatively hide the conflicting items on import, for example say you want to use @Headers annotation which comes form both Retrofit and Dio packages one can do the following on import

```
import 'package:dio/dio.dart' **hide Headers**;
import 'package:retrofit/retrofit.dart';
```

Above says, hide **Headers** in package **dio.dart**. I guess same would apply in all cases with conflicting names
