### ISSUE TITLE
Generator creates `dynamic` fields

### ISSUE THREAD

**Issue by nikitadol** [rrousselGit/freezed#859]
**Describe the bug**
Generator creates `dynamic` fields
state.freezed.dart:
```dart
/// @nodoc
mixin _$State {
  dynamic get id => throw _privateConstructorUsedError;
```

**To Reproduce**

pubspec.yaml: 
```yaml
  build_runner: ^2.3.3
  freezed: ^2.3.2
```

id.dart: 
```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'id.freezed.dart';

@freezed
class Id with _$Id {
  factory Id.point(int value) = PointId;

  factory Id.place(int value) = PlaceId;
}
```

state.dart:
```dart
import 'package:freezed_annotation/freezed_annotation.dart';

import 'id.dart';

part 'state.freezed.dart';

@freezed
class State with _$State {
  factory State.first({
    required PlaceId id,
}) = _First;

  factory State.second({
    required PlaceId id,
}) = _Second;
}
```

**Expected behavior**
state.freezed.dart: 
```dart
/// @nodoc
mixin _$State {
  PlaceId get id => throw _privateConstructorUsedError;
```

**Comment by SunlightBro** [comment]
This is a duplicate but can't find it atm ...

The gist of it is, that you can't use/rely classes/types that need to be generated first in other generated classes.

When you delete all your *.freezed.dart files and hover over `PointId` and `PlaceId` in `Id` your IDE will show an error, because doesn't know their types (haven't been generated).
So that's what the analyzer will tell freezed when triggering build_runner, so freezed doesn't have the necessary information to generate your state file correctly.

build_runner would need to support multiple generation passes to support this, something like:
1. generate id.freezed.dart
2. run analyzer again
3. then generate state.freezed.dart

**Comment by nikitadol** [comment]
If I remove one of the constructors:
```dart
@freezed
class State with _$State {
  factory State.first({
    required PlaceId id,
  }) = _First;
}
```

Then the correct code will be generated:
```dart
/// @nodoc
mixin _$State {
  PlaceId get id => throw _privateConstructorUsedError;
```

**Comment by rrousselGit** [comment]
This is not something which can be easily fixed. The issue is what @SunlightBro explained

For a proper fix to this, it'll have to wait until static metaprogramming. In the meantime, do not rely on the generated classes as input of other generated classes

**Comment by nikitadol** [comment]
But it used to work - it means someone broke something
