### ISSUE TITLE
Add exact field name in error message other than general error message when type error happens

### ISSUE THREAD

**Issue by betimer** [rrousselGit/freezed#963]
**Is your feature request related to a problem? Please describe.**
Currently got error like this
`Expected a value of type 'int', but got one of type 'Null'`

It would be much helpful if getting the error like this to include exact field name

`Expected a value of type 'int', but got one of type 'Null' of field 'bookId'`

**Describe the solution you'd like**
include exact field which causes the error

**Describe alternatives you've considered**
NA

**Comment by rrousselGit** [comment]
Which error?

**Comment by rrousselGit** [comment]
If that's what I think about, this is a compiler error instead of a custom-made error. So I can't do anything about it.

**Comment by rrousselGit** [comment]
What error? Please share some code.

Is it related to fromJson? If so, the error message is on json_serialziable's side. I'm not aware of such an error triggered by Freezed itself

**Comment by adriank** [comment]
@rrousselGit he means that when you have:

```dart
@freezed
class Model with _$Model {
  const factory Model({
    required String name,
    required int age,
  }) = _PubInfoModel;

  factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);
}```

and you get from server:

```json
{
  "name": "a",
  "age": "b"
}
```

You get an Error that doesn't say that the wrong type is in ```age```, but that the wrong type is somewhere inside ```Model```.

To make this case even more usable, there should be a way to handle those cases programmatically somehow so that wrong data would not break apps in production. Now the only option is to wrap everything in try...catch and discard data in full. Would be better to annotate the wrong values and return things that were properly recognized.

**Comment by rrousselGit** [comment]
> To make this case even more usable, there should be a way to handle those cases programmatically somehow so that wrong data would not break apps in production. Now the only option is to wrap everything in try...catch and discard data in full.

You can have a JsonConverter for a specific field.

I am not in control over the error message. If you want a better error message here, you'll have to ask json_serializable. It's the one dealing with decoding
